name: curseforge
on: [workflow_dispatch] # Manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: eclipse-temurin:18-jdk
      options: --user root
    steps:
      - run: apt update && apt install git -y && git --version
      - run: git config --global --add safe.directory /__w/companion/companion

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: FabricMC/fabric-action-scripts@v1
        id: changelog
        with:
          context: changelog
          workflow_id: curseforge.yml

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - uses: gradle/wrapper-validation-action@v1

      - run: ./gradlew build curseforge --stacktrace -Porg.gradle.parallel.threads=4
        env:
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
